/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controladores.Ingredientes_Controller;
import Vistas.Ventana_Aniadir_Ingrediente;
import Utils.DB4OException;
import Utils.ConexionDB4O;
import com.db4o.ObjectSet;
import java.awt.event.MouseEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import Modelo.Ingrediente;

/**
 * 20/5/21 V0.5
 *
 * @author Usuario
 */
public class Ventana_Ingredientes extends javax.swing.JDialog {

    /**
     * Creates new form Ventana_Ingredientes
     */
    public Ventana_Ingredientes() {
        initComponents();
        setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bEliminarIngrediente = new javax.swing.JButton();
        bNuevoIngrediente = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbIngredientes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));

        bEliminarIngrediente.setBackground(new java.awt.Color(0, 0, 0));
        bEliminarIngrediente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bEliminarIngrediente.setForeground(new java.awt.Color(255, 153, 51));
        bEliminarIngrediente.setText("Eliminar");
        bEliminarIngrediente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bEliminarIngredienteMouseClicked(evt);
            }
        });
        bEliminarIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarIngredienteActionPerformed(evt);
            }
        });
        jPanel5.add(bEliminarIngrediente);

        bNuevoIngrediente.setBackground(new java.awt.Color(0, 0, 0));
        bNuevoIngrediente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bNuevoIngrediente.setForeground(new java.awt.Color(255, 153, 51));
        bNuevoIngrediente.setText("Nuevo");
        bNuevoIngrediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNuevoIngredienteActionPerformed(evt);
            }
        });
        jPanel5.add(bNuevoIngrediente);

        jPanel3.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18), new java.awt.Color(255, 153, 51))); // NOI18N

        tbIngredientes.setBackground(new java.awt.Color(204, 204, 204));
        tbIngredientes.setForeground(new java.awt.Color(0, 0, 0));
        tbIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Ingrediente", "Nombre", "Precio", "Comentarios"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbIngredientes.setGridColor(new java.awt.Color(0, 0, 0));
        tbIngredientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIngredientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbIngredientes);
        if (tbIngredientes.getColumnModel().getColumnCount() > 0) {
            tbIngredientes.getColumnModel().getColumn(0).setMinWidth(0);
            tbIngredientes.getColumnModel().getColumn(0).setPreferredWidth(0);
            tbIngredientes.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel3.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Este evento crea una nueva conexión con la base de datos, cambia la
     * localización de la ventana y llama al método cargaTabla.
     *
     * @param evt Se activa cuando se abre la ventana.
     */
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargaTabla();


    }//GEN-LAST:event_formWindowOpened

    private void bNuevoIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNuevoIngredienteActionPerformed
        Ventana_Aniadir_Ingrediente ventana = new Ventana_Aniadir_Ingrediente();
        ventana.setVisible(true);
        cargaTabla();

    }//GEN-LAST:event_bNuevoIngredienteActionPerformed

    private void tbIngredientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIngredientesMouseClicked
           
    }//GEN-LAST:event_tbIngredientesMouseClicked

    private void bEliminarIngredienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarIngredienteActionPerformed
        /*
        Ingrediente ingrediente1 = new Ingrediente();
        int fila = tbIngredientes.getSelectedRow();
        ingrediente1.codigo = tbIngredientes.getModel().getValueAt(fila, 0).toString();
        
        String[] opciones = {"Sí", "No"};

        int x = JOptionPane.showOptionDialog(null, "¿Está seguro de que desea eliminar este ingrediente?",
                "Elija una opción",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, opciones, opciones[0]);

        if (x == 0) {
            System.out.println(x);
            
            ConexionDBO4
            
            bd.conectar();
                
               

           
            
            DefaultTableModel modelo = (DefaultTableModel) tbIngredientes.getModel();

            modelo.removeRow(fila);

            cargaTabla();
        */
    }//GEN-LAST:event_bEliminarIngredienteActionPerformed
    
    private void bEliminarIngredienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEliminarIngredienteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bEliminarIngredienteMouseClicked

    /**
     * Esre método carga la tabla ingredientes y rellena la tabla en la que lo
     * usemos con sus datos.
     */
    private void cargaTabla() {
        
        try {
                                     
           
            Ingredientes_Controller ingC = new Ingredientes_Controller();
            
            ObjectSet<Ingrediente> os = ingC.getListado();                    
            
            DefaultTableModel datos = (DefaultTableModel) tbIngredientes.getModel();

            datos.setRowCount(0);
            
            
            for(Ingrediente i:os){
                ArrayList<String> fila = new ArrayList<String>();
                fila.add(i.codigo);
                fila.add(i.nombre);
                fila.add(String.valueOf(i.precio));
                fila.add(i.descripcion);

                datos.addRow(fila.toArray());
                
            }   
            
                
        } catch (DB4OException ex) {

            Logger.getLogger(Ventana_Ingredientes.class.getName()).log(Level.SEVERE, null,ex);

        }
           
      
    
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEliminarIngrediente;
    private javax.swing.JButton bNuevoIngrediente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbIngredientes;
    // End of variables declaration//GEN-END:variables
}
